# Generated by Django 5.2.10 on 2026-01-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('muscle_group', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('portion_label', models.CharField(default='100g', max_length=40)),
                ('kcal', models.PositiveIntegerField(default=0)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fats_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
    ]
