# Generated by Django 5.2.10 on 2026-01-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnamnesisQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('field_type', models.CharField(choices=[('text', 'text'), ('select', 'select'), ('radio', 'radio')], default='text', max_length=12)),
                ('options', models.CharField(blank=True, help_text="Para select/radio: opções separadas por ';'", max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
