# Generated by Django 5.2.10 on 2026-01-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nome')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Idade')),
                ('weight_kg', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Peso (kg)')),
                ('height_m', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Altura (m)')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('archived', 'Arquivado')], default='active', max_length=16)),
                ('last_activity_at', models.DateField(blank=True, null=True, verbose_name='Última atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.plan')),
            ],
        ),
    ]
