# Generated by Django 5.2.10 on 2026-01-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='crm.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
