# Generated by Django 5.2.10 on 2026-01-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tags', models.CharField(blank=True, help_text='Ex.: Hipertrofia, ABC', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=4)),
                ('reps', models.CharField(default='10-12', max_length=20)),
                ('suggested_load', models.CharField(blank=True, max_length=40)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workoutday')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='workoutday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.workoutplan'),
        ),
        migrations.CreateModel(
            name='ClientWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='crm.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.workoutplan')),
            ],
        ),
    ]
