# Generated by Django 5.2.10 on 2026-03-02 00:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0002_client_extras'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='crm.client')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='accounts.personalprofile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
