# Generated by Django 5.2.10 on 2026-01-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('total_kcal', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets', to='crm.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diets.dietplan')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diets.dietplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_label', models.CharField(default='100g', max_length=40)),
                ('kcal', models.PositiveIntegerField(default=0)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fats_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diets.meal')),
            ],
        ),
    ]
